### PR TITLE
PR JavaScript: To-Do List App

### PR DESCRIPTION
**Pull request by pastorp3**
This is Project #3 in the JavaScript V1.1 curriculum. The purpose of the project is to create a to do list app in which all the content is generated via JavaScript modules. The features implemented in this project were:

- Created the src folder to host all the files necessary for the creation of the page: CSS files and js modules created.
- Created the dist folder to tell webpack where to store the final assets and files for the bundle run.
- Use DOM manipulation to create the content inside each navigation tab.
- Use classes to create a new object
- Loaders used from Webpack:
- style and css for CSS files.

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @pastorp3 
### You have done well so far :clap: However, you have a few issues to fix:-
- [x] DOM-Manipulation and Logic are in separate modules
- [x] It uses localStorage to save todos between sessions
- [x] User can view all to-dos in each project
- [x] User can edit the details of a to-do item
- [x] It has a description
- [x] Resolve the errors in the console
- [x] Fix the start scripts, install all the required dependencies and configure them properly
### Make the changes and submit for another code review. Good luck.
- Happy coding!

**Comment by pastorp3** [comment]
Add review changes

**Review by MarioDena — CHANGES_REQUESTED** [review]
Hello great job on implementing requested changes however there are several features missing form your project.

Changes required 🔴 

- [x] The user should be able to create a TODO item. 
- [x] The user should be able to assign TODO items to a selected project.
- [x] The user should be able to edit properties on selected TODO items.

There are several ways to do this, and form seems to be coded but the features are not present on either the live version or dev version.

- [x] Remember the TODO item should be an Object

- [x] Please use the naming convention introduced to you on the curriculum, you should name your `feature branch` `feature` but this means changing the word `feature` to the name of the actual feature you are working on.

After making the requested changes please resubmit your project for another review.

Cheers! 👍 

Code review by Mario Enrique Delgado Naranjo

**Comment by pastorp3** [comment]
!!!!!!!!!!!! Important !!!!!!!!!!!!!!!!!
On the main screen of the page, you can see the Todo project that it shows all of the projects and task but you cant create a project or a task there, then you have to go to the left side in the input that said Add new project and add it, then click in the name of the project and it will show you in the right side the name of the project and the tasks if you don't have any task it will be blank, to create a new task you can see the input with a placeholder Add new task, and also when you already create a task you can see in the right part the edit icon and delete icon.

Every Project and task are an Object

**Review by rOluochKe — APPROVED** [review]
Hello @pastorp3 
### You got it right, well done :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

**Pull request merged**
